name: rock_star
description: Flutter app for tracking indoor rock climbing (gym agnostic)
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  dart_code_metrics: ^5.7.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true